'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
   await queryInterface.bulkInsert('Pets', [
    {
      type: 'cat',
      age: 4.3,
      sex: 'Ж',
      color: 'рыжий',
      name: 'Минзи',
      coat: 'длинная',
      activity: 4,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1612531822963-7efceefdff4c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1612532279320-9b81f6faab3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1612532275214-e4ca76d0e4d1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'],
      description:'Ласковая, спокойная кошечка Минзи будет вам чудесным другом. Характер у нее по-девичьи нежный и трепетный.\nМинзи с огромной радостью откликается на поглаживание по головке, спинке, любит сидеть на руках, громко и нежно урчит. Будет прекрасным компаньоном для спокойных и ласковых хозяев.\nПриучена к лотку и когтеточке. Знает машину.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 5,
      sex: 'М',
      color: 'рыже-белый',
      name: 'Том',
      coat: 'длинная',
      activity: 2,
      friendliness: false,
      image: ['https://images.unsplash.com/photo-1615531880536-99c0c3a04037?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80', 'https://images.unsplash.com/photo-1615531880567-f119a83e65bb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'],
      description:'Том воспитанный и умный кот, иногда робкий и трогательный.\nКастрирован и приучен к лотку. Может гулять на улице, так и находиться дома. При прогулках находится рядом с местом обитания.\nТак как котик робкий, лучше заводить в семью без других питомцев и детей.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 6.1,
      sex: 'М',
      color: 'рыжий',
      name: 'Борис',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1612532275070-0289d0237681?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1612532276780-14ed318a03e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'],
      description:'Борис спокойный, вальяжный, любит лежать. Он создан для спокойной и размеренной жизни.\nОтлично подойдет людям, которые ценят домашний уют. Котик очень ласковый, навязываться не будет, самодостаточный, но с радостью примет порцию любви и согреет вас своим мурчанием.\nСовершенно не агрессивен ни к людям, ни к другим котикам, подружится с такими же спокойными и добрыми животными.\nПриучен к лотку и когтеточке.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.3,
      sex: 'М',
      color: 'коричнево-белый',
      name: 'Табби',
      coat: 'короткая',
      activity: 5,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1597626133663-53df9633b799?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80', 'https://images.unsplash.com/photo-1597626259989-a11e97b7772d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80'],
      description:'Табби игривый заводной котенок. Столько энергии для игр и забав нет ни у одного подопечного приюта!\nЛюбимое занятие - веселиться с другими котятами, охотиться за игрушками. Табби исследует мир и живет в движении. При этом он очень ласковый, первым идет на контакт с человеком.\nЗнает лоток и когтеточку. Любит высокие поверхности, поэтому для него лучше приобрести высокую когтеточку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.5,
      sex: 'М',
      color: 'коричневый',
      name: 'Бобби',
      coat: 'короткая',
      activity: 2,
      friendliness: false,
      image: ['https://images.unsplash.com/photo-1593288942460-e321b92a6cde?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80'],
      description:'Бобби относится к британской породе, найден случайным образом. Скорее всего потеряли хозяева.\nОсобенностью британской породы является независимость и склонность к одиночеству, поэтому не рекомендуем брать Бобби в семью с детьми и другими питомцами.\nПриучен к лотку, живет в помещении.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.3,
      sex:'М',
      color: 'черно-белый',
      name: 'Глоу',
      coat: 'короткая',
      activity: 4,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1611746280704-c2033bde0849?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80', 'https://images.unsplash.com/photo-1611606977507-9a4dcc83f92d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80', 'https://images.unsplash.com/photo-1611982547704-3df6f1f42051?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'У Глоу необычная внешность, поэтому он сразу привлекает к себе внимание. Он из тех котиков, которым нужно общение и забота, интересные занятия.\nЛюбит поговорить и привлечь внимание голосом.\nПриучается к лотку и когтеточке.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 5.2,
      sex: 'М',
      color: 'рыже-белый',
      name: 'Форвард',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80', 'https://images.unsplash.com/photo-1596854372745-0906a0593bca?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80', 'https://images.unsplash.com/photo-1596854372407-baba7fef6e51?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80'],
      description:'Форвард любит находиться с человеком, наблюдать за ним, также любит ласку и почесушки, совершенно ненавязчивый и неконфликтный спокойный кот, в прошлом был домашним.\nЛюбит покушать, поэтому требует ограничений в еде.\nПриучен к лотку и когтеточке.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.4,
      sex: 'Ж',
      color: 'светлый',
      name: 'Мисси',
      coat: 'короткая',
      activity: 3,
      friendliness: false,
      image: ['https://images.unsplash.com/photo-1572590407445-ac6252f1a5b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1572590285030-0ae6a4715671?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Мисси еще маленькая крошка, но уже свободная и независимая.\nОна с некоторой осторожностью относится к людям и ждет любящих родителей, которым научится доверять, и которые будут готовы к тому, что ей потребуется некоторая адаптация в новом доме.\nК лотку приучена. К когтеточке приучается.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.6,
      sex:'М',
      color: 'трехцветный',
      name: 'Ворсик',
      coat: 'длинная',
      activity: 4,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1596213252429-4a34b4374dd0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1595959923743-d8e09cb56d44?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1596213252414-fad68964011a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1595252849939-1ec8070a354a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Ворсик трехцветный котенок, а значит принесет в дом удачу. А еще, судя по его поведению, - любовь, радость и ласку!\nВорсик контактный котенок, любит общение как с человеком, так и с кошками. С первых дней жизни в приюте он завел себе друзей среди кошек.\nХодит в лоток, знает когтеточку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 3.5,
      sex: 'Ж',
      color: 'коричневый',
      name: 'Соня',
      coat: 'длинная',
      activity: 2,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1546444521-bc4e4296c0f6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80', 'https://images.unsplash.com/photo-1546444521-55ed0a4e6126?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1546444521-26b600b9c749?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Соня хорошая аккуратная кошечка. Знает лоток и когтеточку.\nЛюбит общаться с другими кошками. Ласковая.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 1.5,
      sex: 'М',
      color: 'серо-белый',
      name: 'Феликс',
      coat: 'короткая',
      activity: 5,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1649560677605-e207b639fd44?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8MjZ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60','https://images.unsplash.com/photo-1580784355694-0d5295dcc007?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Феликс любит погулять на улице, подойдет для содержания в своем доме.\nВ туалет привык ходить на улице.\nОхотник, иногда приносит мышек. Игривый, активный и здоровый.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 2.4,
      sex: 'Ж',
      color: 'трехцветный',
      name: 'Дейзи',
      coat: 'длинная',
      activity: 2,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1597784473195-63ad677e6e88?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1597784473166-f8f6280ff6c6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1597784473214-f1bf2ea2d973?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1597784473178-12fc601b3496?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Дейзи очень ласковая кошечка, любит общаться с человеком, ластиться, сидеть на коленках.\nСпокойная, будет находиться рядом с Вами, смотреть телевизор. Предпочитает тепло и уют.\nЗнает лоток и когтеточку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.4,
      sex: 'М',
      color: 'черно-белый',
      name: 'Оскар',
      coat: 'короткая',
      activity: 4,
      friendliness: false,
      image: ['https://images.unsplash.com/photo-1531040825718-5ef13577b4d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1168&q=80', 'https://images.unsplash.com/photo-1531040890822-02403b688175?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Оскар любит веселые игры, может часами носиться за игрушками, преследовать их.\nЧасто пытается перенять внимание с других котов на себя, поэтому лучше взять Оскара в семью без животных.\nКотик хорошо воспитан, точит когти только о когтеточку, ходит в лоток.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 4.4,
      sex: 'М',
      color: 'белый',
      name: 'Гарольд',
      coat: 'короткая',
      activity: 1,
      friendliness: false,
      image: ['https://images.unsplash.com/photo-1531039879349-20d70d192f0f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1531040630173-7cfb894c8eaa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=704&q=80'],
      description:'Гарольд вальяжный кот, любит наблюдать за происходящим со стороны.\nГарольду сложно приходится в обществе других кошек, он также осторожничает при контакте с человеком, но внимание и забота растопят его сердце.\nКотик здоров, красив и воспитан. Знает когтеточку, машину, приучен к лотку. Спокоен на осмотрах у ветеринарных врачей.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 2,
      sex: 'Ж',
      color: 'трехцветный',
      name: 'Моника',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1622015680443-cb4c5bec36b7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1622015681719-9783953d5305?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1622015681746-de2fcfdbf1ed?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Моника спокойная, ласковая кошка, иногда любит поиграть, но больше предпочитает сидеть рядом с человеком.\nТоненьким голосом она сообщает, что пришло время ее погладить!\nЗнает лоток, к когтеточке приучается.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.3,
      sex: 'М',
      color: 'серый',
      name: 'Остин',
      coat: 'короткая',
      activity: 5,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1546180586-7463e25838af?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1546180572-28e937c8128b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80', 'https://images.unsplash.com/photo-1546180558-983a347c84ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Остин-истинный подросток, очень любит веселые игры, мышки, пёрышки, а также внимание людей. Котик очень контактный, ласковый, добрый, дружит с другими животными. А также может поиграть и самостоятельно, навязываться и требовать ласки не будет.\nОтлично подойдет в семью с детьми и станет компаньоном для игр, так же прекрасно уживется с людьми, которые осознают, что котятам в таком возрасте нужно много двигательной активности.\nПриучен к когтеточке и лотку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 3.9,
      sex: 'Ж',
      color: 'коричнево-белый',
      name: 'Марта',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1469533077993-688b0bf0ad33?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1470129913137-0fd7ddb58760?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Грациозная спокойная кошечка, любит помурчать в обществе человека.\nЛадит с другими подопечными приюта, проявляет умеренное любопытство ко всему новому, может поиграть.\nЗнает лоток и когтеточку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 4.5,
      sex: 'М',
      color: 'трехцветный',
      name: 'Семён',
      coat: 'короткая',
      activity: 2,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1617970276851-c6e8acb80b8b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1617457204917-8adf7d298a55?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Семен любит проводить время на улице, поэтому подойдет для содержания в своем доме.\nОтлично ладит в другими животными, в том числе собаками. Спокойно выдерживает чрезмерные ласки детей.\nХодит в туалет на улице, мебель не дерет.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 2.9,
      sex: 'Ж',
      color: 'трехцветный',
      name: 'Черника',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1575034847685-26de555c2691?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1575034755791-e4adff6578cb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80'],
      description:'Черника скромная кошечка, любит наблюдать за человеком и другими кошками. Внутри она очень нежная и ждет, чтобы ее приласкали и полюбили.\nОна станет Вашей ненавязчивой и тихой спутницей. При этом любит и поиграть.\nХодит в лоток, точит когти только о когтеточку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 5.1,
      sex: 'М',
      color: 'коричневый',
      name: 'Бакс',
      coat: 'длинная',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1515172543028-5d19d9e34fba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1515172486498-7a0b147a16c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Бакс озорной кот, любит поиграть с игрушками, а также погулять на улице, поэтому рекомендуем взять Бакса в свой дом./nХодит "по своим делам" на улицу, точит когти также на улице.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 1.5,
      sex: 'М',
      color: 'коричневый',
      name: 'Марс',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1519556883520-8a146529e76f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1520879913969-b462623caab5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Этот красавчик не даст себя пропустить в толпе других. Он умеет привлечь внимание: игрой, лаской, или просто быть рядом и внимательно заглядывать в глаза.\nМарс знает, как выпросить у Вас еще один кусочек вкусняшки или дополнительное поглаживание. И мы почти уверены, что он со временем начнет сам приносить Вам игрушки, чтобы Вы уделили ему внимание. Ведь это всё, что ему нужно: внимание, забота и ласка.\nПриучен к лотку и когтеточке.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 4.6,
      sex: 'М',
      color: 'черно-белый',
      name: 'Бантик',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1588943011511-ef303c037195?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1587420774923-0ccdcf97c37e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1588939783863-ba54fde5d306?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80'],
      description:'Бантик очень домашний, был найден совсем маленьким котёнком и вырос на домашней передержке. Всех тягот и опасностей улицы он не знает. Здоровье крепкое, никогда ни на что не жаловался.\nДоверчив, немного пуглив. Очень разговорчивый котейка. Встречая хозяина с работы, будет обо всем рассказывать, что за день произошло, может немного поворчать.\nСпать предпочитает под боком у хозяина. Игривый. С удовольствием играет с дразнилками, любит погонять мяч с родным братом. Не конфликтный, компанейский кот, с мягким характером.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.4,
      sex: 'М',
      color: 'черный',
      name: 'Уголек',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1604253402434-76a3d93d22d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80', 'https://images.unsplash.com/photo-1604253402617-f53de978f81e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80'],
      description:'Уголек очень-очень ласковый, с удовольствием сидит на руках.\nЛюбит общаться с людьми, доверительно относится даже к незнакомым людям. Ему нравится, когда его хвалят, ласково разговаривают и чешут за ушком.\Приучен к лотку и когтеточке.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 1.9,
      sex: 'М',
      color: 'серо-белый',
      name: 'Пудинг',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1602884954603-6080b9d4c378?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1602884935770-2305ab2f951f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1602884944194-194d17b38475?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Пудинг любит внимание. Когда он спокоен - более серьезного котика еще поискать нужно!\nНаверняка он вырастет умным и активным котом.\nЗнает лоток и когтеточку.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'dog',
      age: 4.6,
      sex: 'Ж',
      color: 'светлый',
      name: 'Грейс',
      coat: 'длинная',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1600716159959-9464d8a6422c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1606161163737-835a52c35c72?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Грейс общительная и спокойная собака. Любит проводить время с другими подопечными приюта, бегать и играть.\nСобачка среднего размера.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'dog',
      age: 4,
      sex: 'Ж',
      color: 'рыже-белый',
      name: 'Люсси',
      coat: 'короткая',
      activity: 2,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1559076717-8ff5a451e9de?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1559076710-bc2066d7c466?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Люсси веселая открытая девочка. Тянется к людям, на прогулках ведет себя послушно и внимательно к человеку.\nБыстро учится командам, спокойная, любит обниматься. Станет отличным другом для детей и других животных.\nРост в холке около 60 см, вес около 30 кг.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'dog',
      age: 7.2,
      sex: 'М',
      color: 'коричневый',
      name: 'Джек',
      coat: 'длинная',
      activity: 3,
      friendliness: false,
      image: ['https://images.unsplash.com/photo-1542052338222-f3dd2ee26152?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1530205329277-2ef7889eb72c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Джек охранный пес. Ведет себя настороженно к незнакомым людям. Сможет оберегать Ваш дом и подходит для жизни на улице.\nПо характеру спокойный, не требует длительных прогулок. Ему сильно не хватает внимания человека, поскорее приезжайте знакомиться!',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'dog',
      age: 1.5,
      sex: 'М',
      color: 'коричнево-белый',
      name: 'Норд',
      coat: 'длинная',
      activity: 4,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1583786587943-429492bd588e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1583786693544-e352f898888d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Норд молодой активный пес, а еще он очень красивый.\nЛюбит долгие прогулки, особенно в лесу. Готов сопровождать Вас куда угодно. Хорошо ладит со всеми подопечными приюта. Проявляет любопытсво к окружающему миру.\nБольшого размера.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'dog',
      age: 3.9,
      sex: 'М',
      color: 'черно-белый',
      name: 'Гром',
      coat: 'короткая',
      activity: 3,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1580918350771-72c6da8b5e2a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1580917959512-c929a13321b2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1580917959519-580f32d58c70?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'],
      description:'Гром - бывшедомашний спокойный пес. Был выброшен хозяевами, так и попал в приют.\nХорошо гуляет на поводке, проявляет охранные способности. Дружелюбен к другим собакам, любит активные игры. Большого размера.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'dog',
      age: 2.7,
      sex: 'Ж',
      color: 'трехцветный',
      name: 'Молли',
      coat: 'короткая',
      activity: 5,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1599908758979-25ba52737fb5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', 'https://images.unsplash.com/photo-1599908758973-b02eb044e5ab?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', ],
      description:'Молли по породе Джек-Рассел-Терьер и попала в приют случайно - пережила потерю своего хозяина. В приюте находится недавно, и мы стараемся внимательно относится к ней и содержать в домашних условиях.\nМолли активная здоровая девочка, любит выполнять разные команды и быстро учится новому. Если Вы ищете верного друга, особенно если у Вас есть дети и другие животные, то приезжайте знакомиться!',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      type: 'cat',
      age: 0.4,
      sex: 'М',
      color: 'коричневый',
      name: 'Пуш',
      coat: 'короткая',
      activity: 4,
      friendliness: true,
      image: ['https://images.unsplash.com/photo-1579962949430-b1ef27810939?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1579962949421-b11c627f8f6e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'https://images.unsplash.com/photo-1579962949542-91f33736528e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'],
      description:'Пуш хоть еще и малыш, но хорошо воспитан и знает, как себя правильно вести!\nОн не дерется и не кусается, не скачет по стенам и не дерет мебель. А еще он созерцательный, но в то же время игривый и озорной.\nТочит когти только о когтеточку, знает лоток, спокойно переносит шум, уже ездил в машине.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
   ], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Pets', null, {});
  }
};
